version: 3.4

services:
  nginx:
    container_name: nginx
    image: nginx:1.16-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./admin-panel/static/admin_custom:/static/admin
    depends_on:
      - server
      - frontend
    command: "nginx -g 'daemon off;'"

  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - configs/config.yml
    volumes:
      - ./:/app:z
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app:z
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - server
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgbackup:
    container_name: pgbackup
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080